shinywaffle/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('shinywaffle.users.urls', namespace='users')),
    url(r'^galleries/',
        include('shinywaffle.galleries.urls', namespace='galleries')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^friendship/', include('friendship.urls')),

    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

shinywaffle/shinywaffle/galleries/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views, ajax

urlpatterns = [
    url(regex=r'^$', view=views.gallery_list_view,
        name='index'),
    url(regex=r'^user/(?P<username>[\w.@+-]+)/$', view=views.gallery_userlist_view,
        name='userlist'),
    url(regex=r'^new/$', view=views.GalleryNewFormView.as_view(),
        name='new'),
    url(regex=r'^display/(?P<pk>\d+)/$',
        view=views.GalleryDetailView.as_view(),
        name='detail'),
    url(regex=r'^(?P<pk>\d+)/image/new/$',
        view=views.GalleryEditFormView.as_view(),
        name='edit'),
    url(regex=r'^images/delete/$', view=ajax.delete_image),
    url(regex=r'^delete/$', view=ajax.delete_gallery),
]

shinywaffle/shinywaffle/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views
from friendship.views import view_friends

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.user_detail,
        name='detail'
    ),
    url(
        regex=r'^(?P<to_username>[\w.@+-]+)/addfriend/$',
        view=views.user_addfriend,
        name='addfriend'
    ),
    url(
        regex=r'^(?P<to_username>[\w.@+-]+)/removefriend/$',
        view=views.user_removefriend,
        name='removefriend'
    ),
    url(
        regex=r'^(?P<to_username>[\w.@+-]+)/addfollow/$',
        view=views.user_addfollow,
        name='addfollow'
    ),
    url(
        regex=r'^(?P<to_username>[\w.@+-]+)/removefollow/$',
        view=views.user_removefollow,
        name='removefollow'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/friends/$',
        view=views.user_friends,
        name='friendlist'
    ),
    url(
        regex=r'^~search/$',
        view=views.search,
        name='search'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^request/accept/(?P<friendship_request_id>\d+)/$',
        view=views.request_accept,
        name='requestaccept',
    ),
    url(
        regex=r'^request/cancel/(?P<friendship_request_id>\d+)/$',
        view=views.request_cancel,
        name='requestcancel',
    ),
    url(
        regex=r'^request/(?P<friendship_request_id>\d+)/$',
        view=views.request_detail,
        name='requestdetail',
    ),
]

shinywaffle/shinywaffle/galleries/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


@python_2_unicode_compatible
class Gallery(models.Model):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    title = models.CharField(
        _('Title of Gallery'), blank=False, max_length=255)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('galleries:index')  # , kwargs={'pk': self.title})


@python_2_unicode_compatible
class Image(models.Model):
    title = models.CharField(_('Title of Image'), blank=False, max_length=255)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    file = models.ImageField(
        upload_to='pictures/', default='pictures/None/no-img.jpg')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('galleries:detail', kwargs={'pk': self.gallery.id})

shinywaffle/shinywaffle/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

shinywaffle/shinywaffle/galleries/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit, HTML
from crispy_forms.bootstrap import InlineField


class GalleryForm(forms.Form):
    gallery_name = forms.CharField(max_length=50)

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        InlineField('gallery_name'),
        ButtonHolder(
            Submit('save_changes', 'Save changes', css_class="btn-primary"),
            HTML('<a class="btn btn-secondary" href={% url "galleries:index" %}>Cancel</a>')
        ),
    )


class ImageForm(forms.Form):
    image_name = forms.CharField(max_length=50)
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        InlineField('image_name'),
        InlineField('images'),
        ButtonHolder(
            Submit('save_changes', 'Save changes', css_class="btn-primary"),
            HTML('<a class="btn btn-secondary" href={% url "galleries:detail" pk=view.gallery.id %}>Cancel</a>')
        ),
    )

shinywaffle/shinywaffle/galleries/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.views.generic import DetailView, ListView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.contrib.auth import get_user_model
from .models import Gallery, Image

from .forms import GalleryForm, ImageForm

from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt


User = get_user_model()

@login_required
def gallery_list_view(request):
    gallery_list = Gallery.objects.all()
    return render(request, 'galleries/gallery_list.html', {'gallery_list': gallery_list})


class GalleryDetailView(LoginRequiredMixin, DetailView):
    model = Gallery

@login_required
def gallery_userlist_view(request, username):
    users = User.objects.get(username=username)
    gallery_list = Gallery.objects.filter(author_id=users.id)
    return render(request, 'galleries/gallery_list.html', {'gallery_list': gallery_list})

class GalleryEditFormView(FormView):
    form_class = ImageForm
    template_name = 'galleries/image_form.html'

    def get_success_url(self):
        return '/galleries/display/{0}/'.format(self.kwargs['pk'])

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        name = request.POST.get('image_name')
        files = request.FILES.getlist('images')
        if form.is_valid():
            for f in files:
                i = Image(title=name, gallery=self.gallery(), file=f)
                i.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def gallery(self):
        return Gallery.objects.get(pk=self.kwargs['pk'])

class GalleryNewFormView(FormView):
    form_class = GalleryForm
    template_name = 'galleries/gallery_form.html'
    success_url = '/galleries/'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        name = request.POST.get('gallery_name')
        if form.is_valid():
            g = Gallery(title=name, author=self.request.user)
            g.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

shinywaffle/shinywaffle/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.conf import settings
from django.http import HttpResponseRedirect

try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
except ImportError:
    from django.contrib.auth.models import User

from friendship.models import Friend, Follow
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages

from friendship.views import view_friends
from friendship.models import Friend, Follow, FriendshipRequest



get_friendship_context_object_name = lambda: getattr(settings, 'FRIENDSHIP_CONTEXT_OBJECT_NAME', 'user')


# class UserDetailView(LoginRequiredMixin, DetailView):
#     model = User
#     # These next two lines tell the view to index lookups by username
#     slug_field = 'username'
#     slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


@login_required
def user_friends(request, username, template_name='users/user_friends.html'):
    user = get_object_or_404(User, username=username)
    friends = Friend.objects.friends(user)
    followers = Follow.objects.followers(user)
    return render(request, template_name, {
        get_friendship_context_object_name(): user,
        'friendship_context_object_name': get_friendship_context_object_name()
    })

@login_required
def user_addfriend(request, to_username):

    if request.method == 'POST':
        to_user = get_object_or_404(User, username=to_username)
        from_user = request.user
        try:
            Friend.objects.add_friend(from_user, to_user)
        except AlreadyExistsError as e:
            messages.add_message(request, messages.ERROR, "%s" % e)

        return redirect('users:detail', username=to_username)

@login_required
def user_removefriend(request, to_username):

    if request.method == 'POST':
        to_user = get_object_or_404(User, username=to_username)
        from_user = request.user
        try:
            Friend.objects.remove_friend(from_user, to_user)
        except AlreadyExistsError as e:
            messages.add_message(request, messages.ERROR, "%s" % e)

        return redirect('users:detail', username=to_username)

@login_required
def user_addfollow(request, to_username):

    if request.method == 'POST':
        followee = User.objects.get(username=to_username)
        follower = request.user
        try:
            Follow.objects.add_follower(follower, followee)
        except AlreadyExistsError as e:
            messages.add_message(request, messages.ERROR, "%s" % e)

        return redirect('users:detail', username=to_username)

@login_required
def user_removefollow(request, to_username):

    if request.method == 'POST':
        followee = User.objects.get(username=to_username)
        follower = request.user
        Follow.objects.remove_follower(follower, followee)

        return redirect('users:detail', username=to_username)

@login_required
def user_detail(request, username, template_name='users/user_detail.html'):
    model = User

    to_user = get_object_or_404(User, username=username)
    friendship_requests = FriendshipRequest.objects.filter(rejected__isnull=True,to_user=to_user.id)
    user = get_object_or_404(model, username=username)
    followers = Follow.objects.followers(user)
    friends = Friend.objects.friends(user)
    return render(request, template_name, {'requests': friendship_requests, 'to_user': user, 'followers': followers, 'friends': friends} )

@login_required
def search(request):
    if request.method == 'POST':
        return user_detail(request, request.POST.get("username"))


@login_required
def request_detail(request, friendship_request_id, template_name='users/user_request.html'):
    """ View a particular friendship request """
    f_request = get_object_or_404(FriendshipRequest, id=friendship_request_id)

    return render(request, template_name, {'friendship_request': f_request})

@login_required
def request_accept(request, friendship_request_id):
    if request.method == 'POST':
        f_request = get_object_or_404(
            FriendshipRequest,
            id=friendship_request_id)
        f_request.accept()

    return redirect('home')

@login_required
def request_reject(request, friendship_request_id):
    """ Reject a friendship request """
    if request.method == 'POST':
        f_request = get_object_or_404(
            FriendshipRequest,
            id=friendship_request_id)
        f_request.reject()

    return redirect('home')

@login_required
def request_cancel(request, friendship_request_id):
    """ Reject a friendship request """
    if request.method == 'POST':
        f_request = get_object_or_404(
            FriendshipRequest,
            pk=friendship_request_id)
        f_request.cancel()

    return redirect('home')

shinywaffle/shinywaffle/templates/galleries/gallery_detail.html
{% extends "base.html" %}
{% load static %}
{% load thumbnail %}

{% block title %}Gallery: {{ gallery.title }}{% endblock %}

{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h2>{{ object.title }}</h2>
        <h5>
          <a href="{% url 'users:detail' object.author %}">{{ object.author }}</a>
        </h5>
        {% for image in gallery.image_set.all %}
          <div id="{{ image.id }}_master" class="image-detail-wrapper col-md-4">
            <a href="{{ image.file.url }}" data-lightbox="{{ gallery.title }}" data-title="{{ image.title }}">
              <img alt="{{ image.title }}" src="{{ image.file | thumbnail_url:'image-detail' }}" width="100%"
                   class="img-responsive img-detail"/>
            </a>
            {% if gallery.author.id == user.id or user.is_superuser %}
              <button id="{{ image.id }}_delete" class="btn btn-danger delete-button-image col-md-12">
                <span aria-hidden="true" class="glyphicon glyphicon-trash delegate"></span>
              </button>
            {% endif %}
          </div>
        {% endfor %}
      </div>
      <div class="container col-md-12">
        <a class="gallery-add-button col-md-12 text-center" href="{% url 'galleries:edit' gallery.id %}"><span
            aria-hidden="true"
            class="glyphicon glyphicon-plus"></span></a>
      </div>
    </div>
  </div>
{% endblock content %}

shinywaffle/shinywaffle/templates/galleries/gallery_form.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}Galleries{% endblock %}

{% block content %}
  <div class="container">
    <h2>Nouvelle gallerie</h2>

    {% crispy form %}

  </div>
{% endblock content %}

shinywaffle/shinywaffle/templates/galleries/gallery_list.html
{% extends "base.html" %}

{% load static i18n %}
{% load thumbnail %}

{% block title %}Galleries{% endblock %}


{% block content %}

  <div class="container">
    <h2>Galleries</h2>
    <div class="list-group">
      {% for gallery in gallery_list %}
        <div id="{{ gallery.id }}_master" class="row list-group-item available">
          <div class="list-group-item-heading list-heading flex">
            <span class="list-title"><a href="{% url 'galleries:detail' pk=gallery.id %}">{{ gallery.title }}</a></span>
            <div class="mid-filler"></div>
            {% if gallery.author == user or user.is_superuser %}
              <!-- <button id="{{ gallery.id }}_update" class="btn btn-info pull-right">
                <span id="{{ gallery.id }}_update-icon" aria-hidden="true"
                      class="glyphicon glyphicon-pencil delegate"></span>
              </button> -->
              <button id="{{ gallery.id }}_delete" class="btn btn-danger delete-button-gallery pull-right">
                <span id="{{ gallery.id }}_delete-icon" aria-hidden="true"
                      class="glyphicon glyphicon-trash delegate"></span>
              </button>
            {% endif %}
          </div>
          {# requête SQL n°1 #}
          {% if gallery.image_set.all.first.file %}
            <a class="col-md-12 gallery-wrapper flex" href="{% url 'galleries:detail' pk=gallery.id %}">
              <img class="offset-sm-3 offset-md-0 col-md-6 col-lg-3 img-responsive img-circle img-strip-main"
                   {# requête SQL n°2 #}
                   src="{{ gallery.image_set.all.first.file | thumbnail_url:'gallery-thumb' }}"
                   {# requête SQL n°3 #}
                   alt="{{ gallery.image_set.all.first.title }}"/>
              <div class="hidden-sm-down col-md-6 col-lg-9 gallery-image-strip">
                {# Ces deux requêtes pourraient être mise en une, un round-trip de moins vers la db #}
                {# SELECT N+1 #}
                {% for i in gallery.image_set.all|slice:"1:3" %}
                  <img class="col-md-6 col-lg-3 img-responsive img-strip"
                       src="{{ i.file | thumbnail_url:'gallery-secondary-thumb' }}"
                       alt="{{ i.title }}"/>
                {% endfor %}
                {# SELECT N+2 #}
                {% for i in gallery.image_set.all|slice:"3:5" %}
                  <img class="col-lg-3 hidden-md-down img-responsive img-strip"
                       src="{{ i.file | thumbnail_url:'gallery-secondary-thumb' }}"
                       alt="{{ i.title }}"/>
                {% endfor %}
              </div>
            </a>
          {% else %}
            <a class="col-md-12 gallery-wrapper flex" href="{% url 'galleries:edit' gallery.id %}">
              <h5 class="text-center">Ooops ! It seems there's no image in here yet. Click to add some.</h5>
            </a>
          {% endif %}
        </div>
      {% empty %}
        <a class="col-md-12 gallery-wrapper flex" href="{% url 'galleries:new' %}">
          <h5 class="text-center">Ooops ! It seems there's no gallery in here yet. Click to add some.</h5>
        </a>
      {% endfor %}
    </div>

    <div class="container col-md-12">
      <a class="gallery-add-button col-md-12 text-center" href="{% url 'galleries:new' %}"><span aria-hidden="true"
                                                                                                 class="glyphicon glyphicon-plus"></span></a>
    </div>
  </div>
{% endblock content %}

shinywaffle/shinywaffle/templates/galleries/image_form.html
{% extends "base.html" %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block title %}Gallery: {{ view.gallery.title }}{% endblock %}

{% block content %}
  <div class="container">
    <h2>Edition de galerie</h2>

    {% crispy form %}

  </div>
{% endblock content %}