shinywaffle/config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'),
        name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'),
        name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # User management
    url(r'^users/', include('shinywaffle.users.urls', namespace='users')),
    url(r'^galleries/',
        include('shinywaffle.galleries.urls', namespace='galleries')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^friendship/', include('friendship.urls')),

    # Your stuff: custom urls includes go here
] + static(
    settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$',
            default_views.bad_request,
            kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$',
            default_views.permission_denied,
            kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$',
            default_views.page_not_found,
            kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

shinywaffle/shinywaffle/galleries/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views, ajax

urlpatterns = [
    url(regex=r'^$', view=views.gallery_list_view,
        name='index'),
    url(regex=r'^user/(?P<username>[\w.@+-]+)/$', view=views.gallery_userlist_view,
        name='userlist'),
    url(regex=r'^new/$', view=views.GalleryNewFormView.as_view(),
        name='new'),
    url(regex=r'^display/(?P<pk>\d+)/$',
        view=views.GalleryDetailView.as_view(),
        name='detail'),
    url(regex=r'^(?P<pk>\d+)/image/new/$',
        view=views.GalleryEditFormView.as_view(),
        name='edit'),
    url(regex=r'^images/delete/$', view=ajax.delete_image),
    url(regex=r'^delete/$', view=ajax.delete_gallery),
]

shinywaffle/shinywaffle/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views
from friendship.views import view_friends

urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.user_detail,
        name='detail'
    ),
    url(
        regex=r'^(?P<to_username>[\w.@+-]+)/addfriend/$',
        view=views.user_addfriend,
        name='addfriend'
    ),
    url(
        regex=r'^(?P<to_username>[\w.@+-]+)/removefriend/$',
        view=views.user_removefriend,
        name='removefriend'
    ),
    url(
        regex=r'^(?P<to_username>[\w.@+-]+)/addfollow/$',
        view=views.user_addfollow,
        name='addfollow'
    ),
    url(
        regex=r'^(?P<to_username>[\w.@+-]+)/removefollow/$',
        view=views.user_removefollow,
        name='removefollow'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/friends/$',
        view=views.user_friends,
        name='friendlist'
    ),
    url(
        regex=r'^~search/$',
        view=views.search,
        name='search'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^request/accept/(?P<friendship_request_id>\d+)/$',
        view=views.request_accept,
        name='requestaccept',
    ),
    url(
        regex=r'^request/cancel/(?P<friendship_request_id>\d+)/$',
        view=views.request_cancel,
        name='requestcancel',
    ),
    url(
        regex=r'^request/(?P<friendship_request_id>\d+)/$',
        view=views.request_detail,
        name='requestdetail',
    ),
]

shinywaffle/shinywaffle/galleries/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _
from django.conf import settings


@python_2_unicode_compatible
class Gallery(models.Model):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    title = models.CharField(
        _('Title of Gallery'), blank=False, max_length=255)

    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE, )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('galleries:index')  # , kwargs={'pk': self.title})


@python_2_unicode_compatible
class Image(models.Model):
    title = models.CharField(_('Title of Image'), blank=False, max_length=255)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE)
    file = models.ImageField(
        upload_to='pictures/', default='pictures/None/no-img.jpg')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('galleries:detail', kwargs={'pk': self.gallery.id})

shinywaffle/shinywaffle/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

shinywaffle/shinywaffle/galleries/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, ButtonHolder, Submit, HTML
from crispy_forms.bootstrap import InlineField


class GalleryForm(forms.Form):
    gallery_name = forms.CharField(max_length=50)

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        InlineField('gallery_name'),
        ButtonHolder(
            Submit('save_changes', 'Save changes', css_class="btn-primary"),
            HTML('<a class="btn btn-secondary" href={% url "galleries:index" %}>Cancel</a>')
        ),
    )


class ImageForm(forms.Form):
    image_name = forms.CharField(max_length=50)
    images = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    helper = FormHelper()
    helper.form_class = 'form-horizontal'
    helper.layout = Layout(
        InlineField('image_name'),
        InlineField('images'),
        ButtonHolder(
            Submit('save_changes', 'Save changes', css_class="btn-primary"),
            HTML('<a class="btn btn-secondary" href={% url "galleries:detail" pk=view.gallery.id %}>Cancel</a>')
        ),
    )

shinywaffle/shinywaffle/galleries/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.views.generic import DetailView, ListView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required

from django.conf import settings
from django.contrib.auth import get_user_model
from .models import Gallery, Image

from .forms import GalleryForm, ImageForm

from django.shortcuts import render, get_object_or_404, redirect
from django.views.decorators.csrf import csrf_exempt


User = get_user_model()

@login_required
def gallery_list_view(request):
    gallery_list = Gallery.objects.all()
    return render(request, 'galleries/gallery_list.html', {'gallery_list': gallery_list})


class GalleryDetailView(LoginRequiredMixin, DetailView):
    model = Gallery

@login_required
def gallery_userlist_view(request, username):
    users = User.objects.get(username=username)
    gallery_list = Gallery.objects.filter(author_id=users.id)
    return render(request, 'galleries/gallery_list.html', {'gallery_list': gallery_list})

class GalleryEditFormView(FormView):
    form_class = ImageForm
    template_name = 'galleries/image_form.html'

    def get_success_url(self):
        return '/galleries/display/{0}/'.format(self.kwargs['pk'])

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        name = request.POST.get('image_name')
        files = request.FILES.getlist('images')
        if form.is_valid():
            for f in files:
                i = Image(title=name, gallery=self.gallery(), file=f)
                i.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def gallery(self):
        return Gallery.objects.get(pk=self.kwargs['pk'])

class GalleryNewFormView(FormView):
    form_class = GalleryForm
    template_name = 'galleries/gallery_form.html'
    success_url = '/galleries/'

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        name = request.POST.get('gallery_name')
        if form.is_valid():
            g = Gallery(title=name, author=self.request.user)
            g.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

shinywaffle/shinywaffle/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView
from django.conf import settings
from django.http import HttpResponseRedirect

try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
except ImportError:
    from django.contrib.auth.models import User

from friendship.models import Friend, Follow
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages

from friendship.views import view_friends
from friendship.models import Friend, Follow, FriendshipRequest



get_friendship_context_object_name = lambda: getattr(settings, 'FRIENDSHIP_CONTEXT_OBJECT_NAME', 'user')


# class UserDetailView(LoginRequiredMixin, DetailView):
#     model = User
#     # These next two lines tell the view to index lookups by username
#     slug_field = 'username'
#     slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


@login_required
def user_friends(request, username, template_name='users/user_friends.html'):
    user = get_object_or_404(User, username=username)
    friends = Friend.objects.friends(user)
    followers = Follow.objects.followers(user)
    return render(request, template_name, {
        get_friendship_context_object_name(): user,
        'friendship_context_object_name': get_friendship_context_object_name()
    })

@login_required
def user_addfriend(request, to_username):

    if request.method == 'POST':
        to_user = get_object_or_404(User, username=to_username)
        from_user = request.user
        try:
            Friend.objects.add_friend(from_user, to_user)
        except AlreadyExistsError as e:
            messages.add_message(request, messages.ERROR, "%s" % e)

        return redirect('users:detail', username=to_username)

@login_required
def user_removefriend(request, to_username):

    if request.method == 'POST':
        to_user = get_object_or_404(User, username=to_username)
        from_user = request.user
        try:
            Friend.objects.remove_friend(from_user, to_user)
        except AlreadyExistsError as e:
            messages.add_message(request, messages.ERROR, "%s" % e)

        return redirect('users:detail', username=to_username)

@login_required
def user_addfollow(request, to_username):

    if request.method == 'POST':
        followee = User.objects.get(username=to_username)
        follower = request.user
        try:
            Follow.objects.add_follower(follower, followee)
        except AlreadyExistsError as e:
            messages.add_message(request, messages.ERROR, "%s" % e)

        return redirect('users:detail', username=to_username)

@login_required
def user_removefollow(request, to_username):

    if request.method == 'POST':
        followee = User.objects.get(username=to_username)
        follower = request.user
        Follow.objects.remove_follower(follower, followee)

        return redirect('users:detail', username=to_username)

@login_required
def user_detail(request, username, template_name='users/user_detail.html'):
    model = User

    to_user = get_object_or_404(User, username=username)
    friendship_requests = FriendshipRequest.objects.filter(rejected__isnull=True,to_user=to_user.id)
    user = get_object_or_404(model, username=username)
    followers = Follow.objects.followers(user)
    friends = Friend.objects.friends(user)
    return render(request, template_name, {'requests': friendship_requests, 'to_user': user, 'followers': followers, 'friends': friends} )

@login_required
def search(request):
    if request.method == 'POST':
        return user_detail(request, request.POST.get("username"))


@login_required
def request_detail(request, friendship_request_id, template_name='users/user_request.html'):
    """ View a particular friendship request """
    f_request = get_object_or_404(FriendshipRequest, id=friendship_request_id)

    return render(request, template_name, {'friendship_request': f_request})

@login_required
def request_accept(request, friendship_request_id):
    if request.method == 'POST':
        f_request = get_object_or_404(
            FriendshipRequest,
            id=friendship_request_id)
        f_request.accept()

    return redirect('home')

@login_required
def request_reject(request, friendship_request_id):
    """ Reject a friendship request """
    if request.method == 'POST':
        f_request = get_object_or_404(
            FriendshipRequest,
            id=friendship_request_id)
        f_request.reject()

    return redirect('home')

@login_required
def request_cancel(request, friendship_request_id):
    """ Reject a friendship request """
    if request.method == 'POST':
        f_request = get_object_or_404(
            FriendshipRequest,
            pk=friendship_request_id)
        f_request.cancel()

    return redirect('home')

shinywaffle/shinywaffle/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

shinywaffle/shinywaffle/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}Shiny Waffle{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

  {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/css/bootstrap.min.css"
          integrity="sha384-2hfp1SzUoho7/TsGGGDaFdsuuDL0LX2hnUp6VkX3CUQ2K4K+xjboZdsXyp4oUHZj" crossorigin="anonymous">

    <!-- Your stuff: Third-party CSS libraries go here -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.9.0/css/lightbox.min.css" rel="stylesheet">

    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/project.min.css' %}" rel="stylesheet">

  {% endblock %}

</head>

<body>

<div class="m-b-1">
  <nav class="navbar navbar-dark navbar-static-top bg-inverse">
    <div class="container">
      <a class="navbar-brand" href="/">Shiny Waffle</a>
      <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse"
              data-target="#bs-navbar-collapse-1">
        &#9776;
      </button>

      <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav pull-xs-right">
          <li class="nav-item">
              <form method="post" action="{% url 'users:search' %}">
                  {% csrf_token %}
                  <input type="text" name="username"/>
                  <input class="btn btn-primary" type="submit" value="Search" />
              </form>
          </li>
          {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'users:detail' request.user.username %}">{% trans "My Profile" %}</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
            </li>
          {% else %}
            <li class="nav-item">
              <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
            </li>
            <li class="nav-item">
              <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
            </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
</div>

<div class="container">
  {% if request.user.is_authenticated %}
    <!-- Fixed navbar -->
    <div id="main-wrapper" class="row">
    <div class="container col-md-3 col-xs-12">
      <div class="navbar navbar-default navbar-fixed-side navbar-fixed-side-left" role="navigation">
        <div class="container">
          <ul class="nav navbar-nav">
            <li class="col-xs-3 col-sm-3 col-md-12">
              <a class="nav-link hidden-xs-down" href="{% url 'home' %}">Home</a>
              <a class="nav-link hidden-sm-up" href="{% url 'home' %}"><span aria-hidden="true"
                                                                             class="glyphicon glyphicon-heart"></span></a>
              <div class="underline"></div>
            </li>
            <li class="col-xs-3 col-sm-3 col-md-12">
              <a class="nav-link hidden-xs-down" href="{% url 'galleries:index' %}">Explore</a>
              <a class="nav-link hidden-sm-up" href="{% url 'galleries:index' %}"><span aria-hidden="true"
                                                                                        class="glyphicon glyphicon-plane"></span></a>
              <div class="underline"></div>
            </li>
            <li class="col-xs-3 col-sm-3 col-md-12">
              <a class="nav-link hidden-xs-down" href="{% url 'galleries:userlist' request.user.username %}">My
                Galleries</a>
              <a class="nav-link hidden-sm-up" href="{% url 'galleries:userlist' request.user.username %}"><span
                  aria-hidden="true" class="glyphicon glyphicon-picture"></span></a>
              <div class="underline"></div>
            </li>
            <li class="col-xs-3 col-sm-3 col-md-12">
              <a class="nav-link hidden-xs-down" href="{% url 'users:friendlist' request.user.username %}">Friends</a>
              <a class="nav-link hidden-sm-up" href="{% url 'users:friendlist' request.user.username %}"><span
                  aria-hidden="true" class="glyphicon glyphicon-user"></span></a>
              <div class="underline"></div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  {% endif %}
  <div class="main-content container col-md-9 col-xs-12">
    {% if messages %}
      {% for message in messages %}
        <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
      {% endfor %}
    {% endif %}

    {% block content %}
      <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}
  </div>
  </div>


</div> <!-- /container -->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
  <!-- Required by Bootstrap v4 Alpha 4 -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"
          integrity="sha384-3ceskX3iaEnIogmQchP8opvBy3Mi7Ce34nWjpBIwVTHfGYWQS9jwHDVRnpKKHJg7"
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
          integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
          crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.4/js/bootstrap.min.js"
          integrity="sha384-VjEeINv9OSwtWFLAtmc4JCtEJXXBub00gtSnszmspDLCtC0I4z4nqz7rEFbIZLLU"
          crossorigin="anonymous"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.9.0/js/lightbox.min.js"></script>

  <!-- place project specific Javascript in this file -->

  <script src="{% static 'js/project.min.js' %}"></script>


{% endblock javascript %}

</body>
</html>